# -*- coding: utf-8 -*-
"""LSTM_pet&text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0yNFtyD_OUsLxv94qAnXiz1xDLjIoiu
"""

!pip install torch torchvision torchaudio transformers datasets \
            scikit-learn pandas numpy tqdm sentencepiece laserembeddings

!python -m laserembeddings download-models

# 1. First, install system-level dependencies
!sudo apt-get install -y cmake build-essential python3-dev

# 2. Then install the Python dependencies
!pip install sacremoses subword-nmt

# 3. Finally install laserembeddings
!pip install laserembeddings==1.1.2

# -----------------------------
# Imports
# -----------------------------
import os, re, random
import pandas as pd
import numpy as np
from tqdm import tqdm
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    classification_report, confusion_matrix, roc_auc_score
)
import matplotlib.pyplot as plt
from laserembeddings import Laser

# -----------------------------
# Section 2: Data Loading & Cleaning
# -----------------------------
# Mount Drive (if using Colab)
from google.colab import drive
drive.mount('/content/drive')

# -----------------------------
# Device configuration
# -----------------------------
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# ----------------- Load Data -----------------
# Train data with labels
train_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/EN_train.csv")
print("Train Columns:", train_df.columns)

# Test data without labels
test_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/EN_test.csv")
print("Test Columns:", test_df.columns)

# Reference test labels
test_ref_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/EN_reference_test.csv")
print("Test Ref Columns:", test_ref_df.columns)

# -----------------------------
# LASER Embeddings
# -----------------------------
from torch.utils.data.sampler import WeightedRandomSampler # Import WeightedRandomSampler

laser = Laser()

def embed_text_pet(df):
    text_emb = laser.embed_sentences(df['text'].astype(str).tolist(), lang='en')
    pet_emb  = laser.embed_sentences(df['PET'].astype(str).tolist(), lang='en')
    return np.concatenate([text_emb, pet_emb], axis=1)

train_embeddings = embed_text_pet(train_df)
train_labels = train_df['label'].values

X_train, X_val, y_train, y_val = train_test_split(
    train_embeddings, train_labels, test_size=0.2, random_state=42, stratify=train_labels
)

# Compute class weights and sampler
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
sample_weights = class_weights[y_train]
sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

test_embeddings = embed_text_pet(test_df)

# -----------------------------
# Dataset & DataLoader
# -----------------------------
class EuphemismDataset(Dataset):
    def __init__(self, embeddings, labels):
        self.embeddings = embeddings
        self.labels = labels

    def __len__(self):
        return len(self.embeddings)

    def __getitem__(self, idx):
        return torch.tensor(self.embeddings[idx], dtype=torch.float32), torch.tensor(self.labels[idx], dtype=torch.long)

train_dataset = EuphemismDataset(X_train, y_train)
val_dataset   = EuphemismDataset(X_val, y_val)
test_dataset  = EuphemismDataset(test_embeddings, np.zeros(len(test_df)))

train_loader = DataLoader(train_dataset, batch_size=64, sampler=sampler)
val_loader   = DataLoader(val_dataset, batch_size=64)
test_loader  = DataLoader(test_dataset, batch_size=64)

# -----------------------------
# LSTM Model Definition
# -----------------------------
class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim=256, num_layers=2, dropout=0.5):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers=num_layers,
                            batch_first=True, dropout=dropout, bidirectional=False)
        self.dropout = nn.Dropout(dropout)
        self.fc1 = nn.Linear(hidden_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        x = x.unsqueeze(1)
        out, (hn, cn) = self.lstm(x)
        h = hn[-1]
        h = self.dropout(F.relu(self.fc1(h)))
        return self.fc2(h).squeeze()

model = LSTMModel(input_dim=train_embeddings.shape[1]).to(device)

# -----------------------------
# Training Setup
# -----------------------------
pos_weight = torch.tensor([class_weights[0] / class_weights[1]], dtype=torch.float32).to(device)
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = AdamW(model.parameters(), lr=1e-3, weight_decay=1e-5)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=2, verbose=True)

scaler = torch.cuda.amp.GradScaler()
num_epochs = 30
early_stop_patience = 7
best_val_f1 = 0
patience_counter = 0

from sklearn.metrics import classification_report
import torch.nn.functional as F

best_val_f1 = 0
best_val_loss = float('inf')
patience_counter = 0

for epoch in range(1, num_epochs + 1):
    model.train()
    total_loss = 0.0
    all_train_preds, all_train_labels = [], []

    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device).float()
        optimizer.zero_grad()

        with torch.cuda.amp.autocast():
            logits = model(X_batch)
            loss = criterion(logits, y_batch)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item()

        preds = (torch.sigmoid(logits) >= 0.5).long().cpu().numpy()
        all_train_preds.extend(preds)
        all_train_labels.extend(y_batch.cpu().long().numpy())

    avg_train_loss = total_loss / len(train_loader)
    train_acc = accuracy_score(all_train_labels, all_train_preds)
    train_precision, train_recall, train_f1, _ = precision_recall_fscore_support(
        all_train_labels, all_train_preds, average='binary'
    )

    # ------------------------
    # Validation
    # ------------------------
    model.eval()
    val_preds, val_labels = [], []
    val_loss = 0.0

    with torch.no_grad(), torch.cuda.amp.autocast():
        for X_batch, y_batch in val_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device).float()
            logits = model(X_batch)
            loss = criterion(logits, y_batch)
            val_loss += loss.item()

            preds = (torch.sigmoid(logits) >= 0.5).long().cpu().numpy()
            val_preds.extend(preds)
            val_labels.extend(y_batch.cpu().long().numpy())

    avg_val_loss = val_loss / len(val_loader)
    val_acc = accuracy_score(val_labels, val_preds)
    val_precision, val_recall, val_f1, _ = precision_recall_fscore_support(
        val_labels, val_preds, average='binary'
    )

    print(f"\nEpoch {epoch}/{num_epochs}")
    print(f"Train Loss: {avg_train_loss:.4f} | Train Acc: {train_acc:.4f} | Train F1: {train_f1:.4f}")
    print(f"Val   Loss: {avg_val_loss:.4f} | Val   Acc: {val_acc:.4f} | Val   F1: {val_f1:.4f}")
    print(classification_report(val_labels, val_preds, target_names=["Non-euphemism", "Euphemism"]))

    scheduler.step(avg_val_loss)

    # ------------------------
    # Early Stopping by F1
    # ------------------------
    if val_f1 > best_val_f1:
        best_val_f1 = val_f1
        best_val_loss = avg_val_loss
        patience_counter = 0
        torch.save(model.state_dict(), 'best_model_f1.pth')
    else:
        patience_counter += 1
        if patience_counter >= early_stop_patience and epoch > 10:
            print("\nEarly stopping triggered due to no F1 improvement.")
            break

## -----------------------------
# Final Validation Evaluation
# -----------------------------
model.load_state_dict(torch.load('best_model.pth'))
model.eval()
val_preds, val_labels = [], []
for X_batch, y_batch in val_loader:
    X_batch = X_batch.to(device)
    logits = model(X_batch)
    preds = (torch.sigmoid(logits) >= 0.5).long().cpu().numpy()
    val_preds.extend(preds)
    val_labels.extend(y_batch.long().numpy())

print("\nFinal Validation Report:")
print(classification_report(val_labels, val_preds, zero_division=0))
cm = confusion_matrix(val_labels, val_preds)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=[0, 1]).plot()
plt.title("Validation Confusion Matrix")
plt.show()

# -----------------------------
# Test Evaluation
# -----------------------------
true_test_labels = test_ref_df['label'].values
model.eval()
test_preds = []
for X_batch, _ in test_loader:
    X_batch = X_batch.to(device)
    logits = model(X_batch)
    preds = (torch.sigmoid(logits) >= 0.5).long().cpu().numpy()
    test_preds.extend(preds)

print("\nTest Set Report:")
print(classification_report(true_test_labels, test_preds, zero_division=0))
cm = confusion_matrix(true_test_labels, test_preds)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=[0, 1]).plot()
plt.title("Test Confusion Matrix")
plt.show()